"use client";

import { useMemo, useState } from "react";

type Finding = { title: string; region: string; text: string; tags: string[] };

const findings: Finding[] = [
  { region: "Crânio", title: "Hidrocefalia", tags: ["congênito", "encéfalo"], text: "Visibiliza-se abaulamento da calota craniana, adelgaçamento de corticais, aumento homogêneo da radiopacidade encefálica e evidenciação da fontanela aberta - imagens que sugerem hidrocefalia." },
  { region: "Crânio", title: "Luxação temporomandibular", tags: ["articulação", "trauma"], text: "Perda da relação articular entre o processo condilar da mandíbula e o processo retroarticular do osso temporal {lado}, com deslocamento rostrodorsal do corpo mandibular - sugestivo de luxação temporomandibular." },
  { region: "Crânio", title: "Doença periodontal", tags: ["dente", "osteólise"], text: "Aumento do espaço periodontal caracterizado por osteólise em osso alveolar do dente {estrutura} - relacionado a doença periodontal." },
  { region: "Crânio", title: "Abscesso periapical", tags: ["dente", "inflamação"], text: "Evidencia-se halo radiotransparente arredondado e delimitado em torno da raiz do dente {estrutura}, podendo estar associado a aumento de volume dos tecidos moles adjacentes - sugestivo de abscesso periapical." },
  { region: "Crânio", title: "Otite média/interna", tags: ["bula timpânica", "inflamação"], text: "Evidencia-se aumento da radiopacidade e espessamento de bula timpânica {lado} - sugestivo de otite média unilateral/bilateral, secundária a otite externa crônica." },
  { region: "Crânio", title: "Tumor nasal", tags: ["neoplasia", "cavidade nasal"], text: "Nota-se aumento da radiopacidade em cavidade nasal {lado}, associado a processo lítico do osso vômer e perda da definição das conchas nasais - imagens que sugerem lesão agressiva, podendo estar relacionada a processo neoplásico. Sugere-se complementação diagnóstica." },
  { region: "Cervical", title: "Prolongamento de palato mole", tags: ["via aérea"], text: "Palato mole em maior evidência, ultrapassando os limites da epiglote - sugestivo de prolongamento de palato mole." },
  { region: "Cervical", title: "Massa traqueal", tags: ["traqueia", "neoplasia"], text: "Visibiliza-se estrutura arredondada de radiopacidade água no trajeto traqueal {segmento}, advinda da parede {face} e projetando-se ao lúmen - pode estar relacionada a neoformação traqueal. Sugere-se realização de demais exames complementares." },
  { region: "Cervical", title: "Ruptura traqueal", tags: ["traqueia", "trauma"], text: "Nota-se descontinuidade da parede {face} do segmento traqueal {segmento}, associada a conteúdo gasoso adjacente e em mediastino cranial, caracterizando pneumomediastino - imagens que sugerem ruptura traqueal." },
  { region: "Coluna", title: "Hemivértebra", tags: ["congênito", "vértebra"], text: "Alteração morfológica do corpo vertebral {estrutura}, apresentando formato de cunha na projeção laterolateral e borboleta na projeção ventrodorsal - relacionada a hemivértebra." },
  { region: "Coluna", title: "Vértebra de transição", tags: ["congênito", "vértebra"], text: "Corpo vertebral {estrutura} apresentando características morfológicas do segmento vertebral adjacente, podendo estar relacionado a toracolização, lombarização ou sacralização - sugestivo de vértebra transicional." },
  { region: "Coluna", title: "Espondilose deformante", tags: ["degenerativo", "coluna"], text: "Proliferação óssea ventral e/ou lateral nos corpos vertebrais, com formação de pontes ósseas em graus variáveis - relacionada a espondilose deformante." },
  { region: "Coluna", title: "Doença do disco intervertebral", tags: ["disco", "degenerativo"], text: "Redução do espaço intervertebral entre {estrutura}, associada a esclerose dos platôs vertebrais e/ou mineralização discal - achados compatíveis com discopatia degenerativa." },
  { region: "Membros", title: "Fratura", tags: ["trauma", "osso"], text: "Presença de linha de fratura em {estrutura}, com desvio {direção} dos fragmentos ósseos e aumento de volume dos tecidos moles adjacentes - sugestivo de fratura." },
  { region: "Membros", title: "Osteoartrose", tags: ["articulação", "degenerativo"], text: "Irregularidade de superfícies articulares, osteófitos periarticulares e discreta esclerose subcondral em {estrutura} - relacionado a doença articular degenerativa." },
  { region: "Membros", title: "Luxação patelar", tags: ["joelho", "articulação"], text: "Deslocamento medial/lateral da patela em relação ao sulco troclear - sugestivo de luxação patelar." },
  { region: "Membros", title: "Displasia coxofemoral", tags: ["quadril", "degenerativo"], text: "Incongruência coxofemoral, remodelamento de cabeça e colo femoral, e cobertura acetabular reduzida em graus variáveis - achados compatíveis com displasia coxofemoral." },
  { region: "Coxal", title: "Fratura pélvica", tags: ["pelve", "trauma"], text: "Identifica-se linha de fratura em {estrutura}, com desalinhamento dos fragmentos e aumento de volume de tecidos moles adjacentes - sugestivo de fratura pélvica." },
  { region: "Tórax", title: "Edema pulmonar", tags: ["pulmão", "cardíaco"], text: "Aumento de radiopacidade pulmonar de padrão intersticial a alveolar, predominante em região perihilar e/ou caudodorsal - compatível com edema pulmonar, a correlacionar clinicamente." },
  { region: "Tórax", title: "Pneumonia", tags: ["pulmão", "inflamação"], text: "Aumento de radiopacidade pulmonar de padrão alveolar, com broncogramas aéreos, predominante em lobos {lobo} - sugestivo de processo inflamatório/infeccioso pulmonar." },
  { region: "Tórax", title: "Cardiomegalia", tags: ["coração"], text: "Aumento da silhueta cardíaca, com índice vertebral cardíaco acima do esperado - compatível com cardiomegalia." },
  { region: "Tórax", title: "Derrame pleural", tags: ["pleura", "líquido"], text: "Aumento de radiopacidade em espaço pleural, com retração de lobos pulmonares e apagamento parcial da silhueta cardíaca - compatível com efusão pleural." },
  { region: "Abdômen", title: "Corpo estranho gastrointestinal", tags: ["trato gastrointestinal", "obstrução"], text: "Presença de estrutura de radiopacidade {radiopacidade} em topografia de trato gastrointestinal, associada ou não a distensão de alças - sugestiva de corpo estranho." },
  { region: "Abdômen", title: "Hepatomegalia", tags: ["fígado"], text: "Aumento da silhueta hepática, com extensão caudal além do arco costal e deslocamento caudal do eixo gástrico - compatível com hepatomegalia." },
  { region: "Abdômen", title: "Esplenomegalia", tags: ["baço"], text: "Aumento da silhueta esplênica, com maior evidência de corpo e cauda do baço - compatível com esplenomegalia." },
  { region: "Abdômen", title: "Urolitíase", tags: ["bexiga", "mineral"], text: "Visibilizam-se estruturas de radiopacidade mineral em topografia de bexiga urinária e/ou uretra - relacionadas a urólitos." },
  { region: "Gestacional", title: "Gestação", tags: ["feto", "gestação"], text: "Identificam-se esqueletos fetais mineralizados em cavidade abdominal, permitindo estimativa radiográfica de {quantidade} concepto(s)." },
  { region: "Outros", title: "Aumento de volume de tecidos moles", tags: ["tecidos moles"], text: "Nota-se aumento de volume e radiopacidade de tecidos moles em topografia de {estrutura}, sem evidências de alteração óssea adjacente nas projeções realizadas." },
];

const regions = ["Todos", ...Array.from(new Set(findings.map((f) => f.region)))];
const replaceTokens = (text: string) => text.replace(/\{lado\}/g, "esquerdo/direito").replace(/\{estrutura\}/g, "[estrutura]").replace(/\{segmento\}/g, "cervical/torácico").replace(/\{face\}/g, "dorsal/ventral").replace(/\{direção\}/g, "[direção]").replace(/\{lobo\}/g, "[lobo]").replace(/\{radiopacidade\}/g, "mineral/metal").replace(/\{quantidade\}/g, "[número]");

export default function Home() {
  const [query, setQuery] = useState(""); const [region, setRegion] = useState("Todos"); const [selected, setSelected] = useState<Finding[]>([]); const [patient, setPatient] = useState("");
  const filtered = useMemo(() => findings.filter((f) => (region === "Todos" || f.region === region) && `${f.title} ${f.region} ${f.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [query, region]);
  const report = `LAUDO RADIOGRÁFICO${patient ? `\nPaciente: ${patient}` : ""}\n\nACHADOS:\n${selected.map((f, i) => `${i + 1}. ${replaceTokens(f.text)}`).join("\n\n") || "Selecione achados na biblioteca ao lado para iniciar o laudo."}\n\nImpressão diagnóstica: Correlacionar os achados aos dados clínicos e, quando indicado, a exames complementares.`;
  const toggle = (f: Finding) => setSelected((s) => s.some((x) => x.title === f.title) ? s.filter((x) => x.title !== f.title) : [...s, f]);
  const copy = async () => { await navigator.clipboard.writeText(report); alert("Laudo copiado para a área de transferência."); };
  return <main>
    <header><div className="brand"><span className="brand-mark">R</span><span>RADIO<span>VET</span></span></div><div className="header-note">Biblioteca clínica para apoio descritivo</div></header>
    <section className="hero"><div><p className="eyebrow">LAUDOS RADIOGRÁFICOS VETERINÁRIOS</p><h1>Do achado ao laudo,<br/><em>com clareza.</em></h1><p className="hero-copy">Pesquise modelos de descrição, selecione os achados e construa um texto clínico consistente em poucos passos.</p></div><div className="hero-card"><span>Biblioteca organizada</span><strong>{findings.length} modelos essenciais</strong><small>Crânio · Coluna · Tórax · Abdômen · Membros</small></div></section>
    <section className="workspace"><aside><p className="section-label">1. ENCONTRE O ACHADO</p><label className="search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por alteração, região..." /></label><div className="filters">{regions.map((r) => <button key={r} className={region === r ? "active" : ""} onClick={() => setRegion(r)}>{r}</button>)}</div><div className="result-count">{filtered.length} modelos encontrados</div><div className="cards">{filtered.map((f) => <article key={f.title} className={selected.some(x => x.title === f.title) ? "selected" : ""} onClick={() => toggle(f)}><div className="card-top"><span>{f.region}</span><b>{selected.some(x => x.title === f.title) ? "✓ ADICIONADO" : "+ ADICIONAR"}</b></div><h3>{f.title}</h3><p>{f.text}</p><div className="tags">{f.tags.map(t => <i key={t}>{t}</i>)}</div></article>)}</div></aside>
      <section className="report"><div className="report-top"><div><p className="section-label">2. MONTE O LAUDO</p><h2>Seu relatório</h2></div><button className="clear" onClick={() => setSelected([])}>Limpar</button></div><input className="patient" value={patient} onChange={(e) => setPatient(e.target.value)} placeholder="Paciente (opcional)" /><pre>{report}</pre><div className="report-actions"><button className="secondary" onClick={() => { const b=new Blob([report],{type:"text/plain"}); const a=document.createElement("a"); a.href=URL.createObjectURL(b); a.download="laudo-radiografico.txt"; a.click(); }}>Baixar .txt</button><button className="primary" onClick={copy}>Copiar laudo</button></div><p className="disclaimer">Ferramenta de apoio. A interpretação e responsabilidade técnica são exclusivas do médico-veterinário.</p></section>
    </section>
  </main>;
}
