export type ThrallContext = {
  chapter: string;
  chapterTitle: string;
  summary: string;
  mechanism: string;
  confirm: string[];
  pitfalls: string[];
  nextStep: string;
  evidence: string;
};

export type ThrallStudyGuide = {
  id: string;
  title: string;
  chapters: string;
  introduction: string;
  essentials: string[];
  sequence: string[];
  traps: string[];
};

export const thrallStudyGuides: ThrallStudyGuide[] = [
  {
    id: "interpretacao",
    title: "Método de interpretação",
    chapters: "Capítulos 5, 7, 14, 25 e 35",
    introduction: "A leitura ganha consistência quando a imagem é descrita antes de receber um diagnóstico. A alteração deve ser localizada e caracterizada por tamanho, forma, margens, radiopacidade, número, distribuição e efeito sobre estruturas vizinhas.",
    essentials: [
      "Confirme identificação, projeções, posicionamento, colimação, exposição e presença de artefatos.",
      "Use as cinco radiopacidades básicas: gás, gordura, tecido mole/líquido, mineral e metal.",
      "Pense em três dimensões e confirme o achado em projeções ortogonais sempre que possível.",
      "Separe descrição observável, interpretação e recomendação clínica.",
    ],
    sequence: ["Qual é a estrutura?", "Onde exatamente está?", "Como sua radiopacidade e contorno mudaram?", "Qual a distribuição?", "Que estruturas foram deslocadas?", "Qual conclusão é sustentada pela imagem?"],
    traps: ["Satisfação de busca após encontrar a primeira alteração.", "Chamar doença antes de descrever o sinal.", "Confundir sobreposição, rotação ou exposição inadequada com lesão."],
  },
  {
    id: "osso",
    title: "Lesões ósseas e agressividade",
    chapters: "Capítulos 14, 16 e 17",
    introduction: "Lesões ósseas devem ser classificadas pela velocidade aparente do processo. Zona de transição, padrão de lise, reação periosteal, integridade cortical, matriz e distribuição são mais úteis do que um único sinal isolado.",
    essentials: [
      "Zona de transição curta e margens escleróticas favorecem crescimento lento; transição longa e margens indistintas elevam a suspeita de agressividade.",
      "Lise geográfica, permeativa ou roída por traça representa graus crescentes de indefinição, não diagnósticos isolados.",
      "Reação periosteal lisa e contínua tende a ser menos agressiva; interrompida, amorfa ou espiculada merece maior atenção.",
      "Defina se a lesão é monostótica, poliostótica, articular, metafisária, diafisária ou epifisária.",
    ],
    sequence: ["Localização no osso", "Margens e zona de transição", "Lise", "Proliferação periosteal", "Cortical", "Matriz", "Tecidos moles", "Distribuição"],
    traps: ["Tentar diferenciar neoplasia de infecção apenas pela radiografia.", "Ignorar idade e localização anatômica.", "Chamar osteólise discreta sem comparar projeções e estruturas adjacentes."],
  },
  {
    id: "fraturas",
    title: "Fraturas e consolidação",
    chapters: "Capítulo 16",
    introduction: "A descrição deve permitir reconstruir a fratura sem ver a imagem. Inclua osso, lado, segmento, orientação, extensão, deslocamento, comunicação com o meio, envolvimento articular e alterações de tecidos moles.",
    essentials: [
      "Descreva simples ou cominutiva; completa ou incompleta; transversal, oblíqua, espiral ou segmentar.",
      "Informe desvio do fragmento distal em relação ao proximal, além de angulação, rotação e encurtamento.",
      "Em animais jovens, classifique o envolvimento fisário e procure lesões simultâneas.",
      "No acompanhamento, avalie ponte cortical, remodelamento, linha de fratura, estabilidade do implante e sinais de infecção.",
    ],
    sequence: ["Osso e lado", "Terço", "Configuração", "Extensão", "Deslocamento", "Articulação", "Tecidos moles", "Implantes/calo"],
    traps: ["Confundir sobreposição com linha de fratura.", "Não radiografar articulações proximal e distal.", "Interpretar calo exuberante sem considerar estabilidade mecânica."],
  },
  {
    id: "articulacoes",
    title: "Doença articular",
    chapters: "Capítulo 18",
    introduction: "A radiografia demonstra principalmente consequências ósseas e de tecidos moles. Cartilagem, sinóvia, meniscos e ligamentos podem exigir ultrassom, artrografia, tomografia ou ressonância.",
    essentials: [
      "Procure efusão, espessamento capsular, alteração do espaço articular, osso subcondral, osteófitos, enteseófitos e corpos mineralizados.",
      "Osteoartrite costuma produzir osteófitos e esclerose subcondral; artrite agressiva pode causar erosões e irregularidade das margens.",
      "Compare articulação contralateral quando a simetria puder ajudar.",
      "A ausência de alteração radiográfica não exclui lesão ligamentar ou cartilaginosa inicial.",
    ],
    sequence: ["Alinhamento", "Espaço articular", "Efusão/cápsula", "Osso subcondral", "Margens", "Enteses", "Corpos livres", "Musculatura"],
    traps: ["Supervalorizar pequena irregularidade de posicionamento.", "Usar redução do espaço articular em projeção não padronizada.", "Excluir doença de partes moles porque o osso parece normal."],
  },
  {
    id: "torax",
    title: "Leitura sistemática do tórax",
    chapters: "Capítulos 25 a 33",
    introduction: "A interpretação torácica depende da qualidade técnica e da distribuição. Parede torácica, espaço pleural, mediastino, coração, vasos, vias aéreas e pulmões devem ser revistos em sequência fixa.",
    essentials: [
      "Prefira imagens em inspiração e avalie rotação antes de medir ou comparar.",
      "Classifique o padrão pulmonar predominante como bronquial, intersticial ou alveolar e descreva sua distribuição.",
      "Use vasos, fissuras pleurais, posição dos lobos e silhuetas de órgãos para localizar a alteração.",
      "Considere idade, conformação, fase respiratória e decúbito como modificadores da aparência.",
    ],
    sequence: ["Técnica", "Parede", "Pleura", "Mediastino", "Coração e vasos", "Traqueia e brônquios", "Pulmões", "Diafragma"],
    traps: ["Atelectasia de decúbito simulando pneumonia.", "Expiração simulando cardiomegalia e padrão pulmonar.", "Dobras cutâneas simulando pneumotórax."],
  },
  {
    id: "pulmao",
    title: "Padrões pulmonares",
    chapters: "Capítulo 33",
    introduction: "O padrão descreve qual componente pulmonar domina a imagem; a distribuição e o contexto clínico estreitam os diferenciais. Padrões mistos são comuns e o mais importante deve ser citado primeiro.",
    essentials: [
      "Bronquial: paredes brônquicas espessadas, vistas como trilhos e anéis.",
      "Intersticial não estruturado: aumento difuso ou focal da radiopacidade sem apagar completamente vasos.",
      "Intersticial estruturado: nódulos ou massas; avalie número, tamanho, margens e cavitação.",
      "Alveolar: apagamento vascular, broncogramas aéreos e sinal lobar.",
    ],
    sequence: ["Padrão", "Intensidade", "Distribuição craniocaudal", "Distribuição dorsoventral", "Simetria", "Vasos", "Vias aéreas", "Evolução"],
    traps: ["Usar o padrão como diagnóstico final.", "Não reconhecer padrão misto.", "Confundir vasos vistos de frente com nódulos."],
  },
  {
    id: "abdomen",
    title: "Leitura sistemática do abdômen",
    chapters: "Capítulos 35 a 45",
    introduction: "A leitura abdominal começa pelo detalhe seroso e segue tamanho, forma, margens, posição e radiopacidade de cada órgão. Deslocamentos e efeitos de massa ajudam a localizar a origem.",
    essentials: [
      "Avalie detalhe seroso considerando idade, gordura abdominal, técnica e presença de líquido.",
      "Use o padrão de gás para distinguir estômago, intestino delgado e cólon e para reconhecer deslocamentos.",
      "Descreva organomegalia com sinais objetivos e o efeito sobre órgãos vizinhos.",
      "Radiografia e ultrassonografia são complementares; a segunda caracteriza parênquima e conteúdo com maior precisão.",
    ],
    sequence: ["Técnica", "Serosa/peritônio", "Fígado e baço", "Rins", "Bexiga", "Estômago", "Intestino delgado", "Cólon", "Reprodutor", "Esqueleto"],
    traps: ["Perda de detalhe por paciente jovem ou magro simulando efusão.", "Conteúdo alimentar simulando corpo estranho.", "Concluir obstrução sem avaliar distribuição e persistência da dilatação."],
  },
  {
    id: "cranio_coluna",
    title: "Crânio e coluna",
    chapters: "Capítulos 7, 8 e 11",
    introduction: "A sobreposição torna crânio e coluna especialmente dependentes de posicionamento e projeções complementares. Simetria, alinhamento, corticais, espaços e foramens devem ser comparados de forma sistemática.",
    essentials: [
      "No crânio, compare lados e acompanhe cavidades nasais, vômer, seios, bulas, mandíbulas e arcadas dentárias.",
      "Na coluna, avalie alinhamento em duas projeções, espaços intervertebrais, placas terminais, processos e canal vertebral.",
      "Radiografias têm baixa sensibilidade para o encéfalo, medula e várias doenças discais.",
      "Tomografia é superior para osso complexo; ressonância é superior para encéfalo, medula e tecidos moles.",
    ],
    sequence: ["Posicionamento", "Simetria/alinhamento", "Cortical e trabeculado", "Espaços/cavidades", "Proliferação ou lise", "Tecidos moles", "Limitações"],
    traps: ["Rotação simulando assimetria.", "Sobreposição escondendo lise discreta.", "Excluir compressão neurológica com base apenas em radiografias."],
  },
];

const regionBase: Record<string, ThrallContext> = {
  "Crânio": {
    chapter: "Capítulos 7 e 8",
    chapterTitle: "Esqueleto axial e cavidades craniana/nasal",
    summary: "A interpretação do crânio deve ser comparativa e sistemática porque a sobreposição é intensa. Assimetria, perda do trabeculado, lise, proliferação e deslocamentos são sinais mais confiáveis quando confirmados em projeções complementares.",
    mechanism: "A alteração radiográfica resulta da mudança de mineralização, espessura óssea, conteúdo das cavidades ou efeito de massa sobre estruturas adjacentes.",
    confirm: ["Confirme simetria e posicionamento.", "Acompanhe corticais e limites das cavidades.", "Procure lise, proliferação, deslocamento e alteração de radiopacidade.", "Compare dentes, bulas, articulações e tecidos moles."],
    pitfalls: ["Rotação pode simular assimetria.", "Sobreposição pode ocultar lesões precoces.", "A radiografia é limitada para encéfalo e tecidos moles profundos."],
    nextStep: "Tomografia é especialmente útil para anatomia óssea complexa; ressonância é preferível quando o encéfalo ou outros tecidos moles são a principal dúvida.",
    evidence: "Síntese de estudo baseada nos capítulos 7 e 8 de Thrall, 6ª edição.",
  },
  "Cervical": {
    chapter: "Capítulos 26 e 27",
    chapterTitle: "Faringe, laringe, traqueia e esôfago",
    summary: "A avaliação cervical deve seguir o lúmen da faringe à entrada do tórax, observando diâmetro, continuidade, conteúdo, deslocamento e tecidos moles adjacentes.",
    mechanism: "Redução do lúmen, espessamento de parede, conteúdo intraluminal, gás extraluminal ou efeito de massa geram os principais sinais radiográficos.",
    confirm: ["Compare projeções lateral e ventrodorsal.", "Siga o lúmen sem saltar segmentos.", "Procure desvio, estreitamento, dilatação e gás em tecidos moles.", "Avalie estruturas ósseas e hioides."],
    pitfalls: ["Fase respiratória e posição do pescoço mudam o diâmetro das vias aéreas.", "Sobreposição pode esconder corpos estranhos pouco radiopacos.", "Alterações dinâmicas podem exigir fluoroscopia."],
    nextStep: "Fluoroscopia, endoscopia, ultrassom ou tomografia podem ser necessários conforme o segmento e a suspeita.",
    evidence: "Síntese de estudo baseada nos capítulos 26 e 27 de Thrall, 6ª edição.",
  },
  "Coluna": {
    chapter: "Capítulos 7, 11 e 12",
    chapterTitle: "Coluna vertebral e medula espinhal",
    summary: "Radiografias avaliam principalmente osso, alinhamento e espaços. A medula e a maioria das compressões precisam de tomografia, mielografia ou ressonância para caracterização.",
    mechanism: "Mudanças de alinhamento, morfologia, espaço intervertebral, placas terminais, proliferação ou lise refletem trauma, degeneração, infecção, desenvolvimento ou neoplasia.",
    confirm: ["Localize a vértebra e o segmento.", "Confirme alinhamento em duas projeções.", "Compare espaços e placas terminais.", "Revise processos articulares, forames e tecidos paravertebrais."],
    pitfalls: ["Obliquidade cria falsos desalinhamentos.", "Espaço reduzido isolado é inespecífico.", "Radiografia normal não exclui doença medular ou discal."],
    nextStep: "Ressonância é preferível para medula e disco; tomografia é muito útil em trauma e detalhes ósseos.",
    evidence: "Síntese de estudo baseada nos capítulos 7, 11 e 12 de Thrall, 6ª edição.",
  },
  "Membros": {
    chapter: "Capítulos 14 a 18",
    chapterTitle: "Esqueleto apendicular, fraturas, osso e articulações",
    summary: "A análise deve localizar o processo e classificar agressividade, alinhamento e envolvimento articular. Cortical, medular, periósteo, osso subcondral e tecidos moles formam uma única unidade de leitura.",
    mechanism: "Lise, produção óssea, remodelamento, alteração subcondral, efusão e deslocamento refletem a velocidade e o compartimento predominante da doença.",
    confirm: ["Defina osso, lado e segmento.", "Avalie zona de transição e padrão de lise.", "Caracterize reação periosteal e cortical.", "Inclua articulações e tecidos moles adjacentes."],
    pitfalls: ["Infecção e neoplasia podem ser indistinguíveis.", "Projeção única subestima extensão e fraturas.", "Lesões de cartilagem e ligamentos podem não ser visíveis."],
    nextStep: "Projeções adicionais, ultrassom, tomografia, ressonância, citologia ou biópsia dependem do compartimento e da agressividade.",
    evidence: "Síntese de estudo baseada nos capítulos 14 a 18 de Thrall, 6ª edição.",
  },
  "Coxal": {
    chapter: "Capítulo 18",
    chapterTitle: "Doença articular e displasia coxofemoral",
    summary: "A pelve deve ser avaliada quanto à simetria, congruência, cobertura acetabular, remodelamento, osteófitos e alinhamento sacroilíaco.",
    mechanism: "Frouxidão, incongruência, trauma ou alteração fisária modificam a relação entre acetábulo e cabeça femoral e podem produzir osteoartrite secundária.",
    confirm: ["Confirme posicionamento pélvico simétrico.", "Compare cobertura acetabular bilateral.", "Avalie cabeça, colo e acetábulo.", "Procure osteófitos e esclerose subcondral."],
    pitfalls: ["Rotação pélvica simula subluxação.", "Sedação e técnica influenciam a avaliação de frouxidão.", "Ausência de osteófitos não exclui instabilidade inicial."],
    nextStep: "Projeções de distração, tomografia ou avaliação ortopédica podem complementar casos selecionados.",
    evidence: "Síntese de estudo baseada no capítulo 18 de Thrall, 6ª edição.",
  },
  "Tórax": {
    chapter: "Capítulos 25 a 33",
    chapterTitle: "Interpretação torácica",
    summary: "A distribuição da alteração é tão importante quanto o padrão. A qualidade técnica, fase respiratória e decúbito devem ser considerados antes de atribuir significado à radiopacidade pulmonar ou ao tamanho cardíaco.",
    mechanism: "Mudanças de ar, líquido, células, tecido ou volume nos compartimentos torácicos alteram contraste, silhuetas, posição dos lobos e visibilidade vascular.",
    confirm: ["Julgue inspiração, rotação e exposição.", "Localize a alteração por compartimento.", "Classifique o padrão pulmonar quando aplicável.", "Descreva distribuição, intensidade e efeito sobre vasos e silhuetas."],
    pitfalls: ["Expiração simula cardiomegalia.", "Atelectasia de decúbito simula doença pulmonar.", "Dobras cutâneas simulam pneumotórax."],
    nextStep: "Ultrassom, ecocardiografia, tomografia, fluoroscopia, lavagem de vias aéreas ou amostragem podem ser indicados pelo compartimento.",
    evidence: "Síntese de estudo baseada nos capítulos 25 a 33 de Thrall, 6ª edição.",
  },
  "Abdômen": {
    chapter: "Capítulos 35 a 45",
    chapterTitle: "Interpretação abdominal",
    summary: "Detalhe seroso, tamanho, forma, margens, posição, radiopacidade e efeito de massa orientam a localização. O padrão de gás é uma ferramenta anatômica e diagnóstica central.",
    mechanism: "Líquido, gás, mineralização, organomegalia e massas mudam o contraste e deslocam órgãos de maneira previsível.",
    confirm: ["Avalie detalhe seroso e técnica.", "Localize pelo deslocamento de órgãos.", "Descreva tamanho, forma, margem e radiopacidade.", "Analise distribuição do gás gastrointestinal."],
    pitfalls: ["Paciente jovem ou magro pode ter pouco detalhe seroso.", "Conteúdo alimentar simula material estranho.", "Radiografia não caracteriza bem o parênquima."],
    nextStep: "Ultrassonografia é o complemento mais frequente; contraste, tomografia ou endoscopia dependem do órgão e da suspeita.",
    evidence: "Síntese de estudo baseada nos capítulos 35 a 45 de Thrall, 6ª edição.",
  },
  "Gestacional": {
    chapter: "Capítulo 42",
    chapterTitle: "Útero, ovários e trato reprodutivo",
    summary: "A radiografia é mais útil após mineralização fetal, permitindo contagem aproximada, posição e relação fetopélvica. Viabilidade é melhor avaliada por ultrassom.",
    mechanism: "Mineralização progressiva torna crânio, coluna e esqueleto apendicular fetais visíveis; gás fetal ou desalinhamento ósseo podem acompanhar morte fetal.",
    confirm: ["Conte crânios e colunas individualizáveis.", "Avalie posição e apresentação.", "Compare diâmetro fetal e canal pélvico.", "Procure gás fetal ou perda de organização esquelética."],
    pitfalls: ["Sobreposição dificulta a contagem.", "Radiografia não confirma batimentos ou perfusão.", "Estimativa gestacional isolada tem margem de erro."],
    nextStep: "Ultrassonografia é indicada para viabilidade, frequência cardíaca e avaliação de tecidos moles.",
    evidence: "Síntese de estudo baseada no capítulo 42 de Thrall, 6ª edição.",
  },
  "Outros": {
    chapter: "Capítulos 5 e 14",
    chapterTitle: "Princípios gerais de interpretação",
    summary: "Achados diversos devem ser descritos por localização, número, tamanho, forma, margens, radiopacidade e relação com estruturas próximas.",
    mechanism: "A radiopacidade e a distribuição ajudam a distinguir gás, gordura, tecido mole, mineral e metal e a inferir o compartimento envolvido.",
    confirm: ["Localize em duas projeções.", "Defina material e radiopacidade.", "Avalie reação óssea e tecidos moles.", "Relacione com histórico de cirurgia ou trauma."],
    pitfalls: ["Sobreposição pode falsear a localização.", "Material externo pode simular corpo estranho.", "A radiografia não define composição histológica."],
    nextStep: "A complementação depende da estrutura: ultrassom para tecidos moles, tomografia para localização tridimensional e amostragem para definição etiológica.",
    evidence: "Síntese de estudo baseada nos capítulos 5 e 14 de Thrall, 6ª edição.",
  },
};

type ContextRule = {
  test: RegExp;
  priority?: number;
  chapter?: string;
  chapterTitle?: string;
  summary?: string;
  mechanism?: string;
  confirm?: string[];
  pitfalls?: string[];
  nextStep?: string;
};

const rules: ContextRule[] = [
  {
    test: /hidrocefalia/i,
    priority: 4,
    chapter: "Capítulo 8",
    chapterTitle: "Cavidades craniana e nasal",
    summary: "A radiografia pode demonstrar aumento e abaulamento da calota, adelgaçamento cortical e fontanela persistente, mas não quantifica ventrículos nem caracteriza o encéfalo.",
    mechanism: "O aumento crônico do volume intracraniano durante o desenvolvimento modifica a forma e a espessura da calota.",
    confirm: ["Avalie formato e espessura da calota.", "Procure fontanela persistente.", "Compare com conformação racial e idade.", "Revise sinais de outras malformações."],
    pitfalls: ["Braquicefalia pode modificar a forma do crânio.", "Radiografia normal não exclui ventriculomegalia.", "A aparência óssea não mede gravidade neurológica."],
    nextStep: "Ressonância caracteriza ventrículos e encéfalo; ultrassom transfontanelar pode ser útil quando há janela adequada.",
  },
  {
    test: /displasia do occipital/i,
    priority: 4,
    chapter: "Capítulo 8",
    chapterTitle: "Cavidades craniana e nasal",
    summary: "A extensão dorsal do forame magno e a morfologia do occipital podem ser sugeridas radiograficamente, mas a sobreposição limita a avaliação.",
    mechanism: "Desenvolvimento anormal do osso occipital modifica o contorno do forame magno e a fossa caudal.",
    confirm: ["Avalie simetria do occipital.", "Procure extensão dorsal do forame magno.", "Considere conformação braquicefálica.", "Relacione com sinais neurológicos."],
    pitfalls: ["Posicionamento assimétrico altera o contorno.", "A alteração pode ser incidental.", "Radiografia não avalia compressão de tecidos neurais."],
    nextStep: "Tomografia define o osso; ressonância avalia cerebelo, tronco encefálico e possível repercussão neural.",
  },
  {
    test: /hiperostose da calota|osteopatia craniomandibular/i,
    priority: 4,
    chapter: "Capítulo 8",
    chapterTitle: "Cavidades craniana e nasal",
    summary: "Proliferação e espessamento cranianos devem ser descritos por distribuição, simetria, superfície, estruturas acometidas e possível redução de cavidades.",
    mechanism: "Produção óssea reativa ou doença proliferativa aumenta espessura e radiopacidade e pode remodelar mandíbula, bulas ou calota.",
    confirm: ["Mapeie ossos acometidos.", "Defina lisa ou irregular.", "Avalie simetria e progressão.", "Procure redução de cavidades e envolvimento mandibular."],
    pitfalls: ["Sobreposição exagera espessamento.", "Doenças diferentes podem compartilhar proliferação.", "Idade e raça mudam os diferenciais."],
    nextStep: "Tomografia define extensão e relação com cavidades; biópsia é considerada quando o padrão e a evolução não são típicos.",
  },
  {
    test: /espondilomielopatia|instabilidade lombossacra|subluxação atlantoaxial|espondilolistese/i,
    priority: 4,
    chapter: "Capítulos 11 e 12",
    chapterTitle: "Instabilidade vertebral e medula",
    summary: "Alterações de alinhamento e remodelamento podem sugerir instabilidade, mas a compressão neural e o componente dinâmico não são definidos por radiografias simples.",
    mechanism: "Instabilidade, malformação ou degeneração modifica a relação entre corpos, facetas e canal e pode gerar proliferação secundária.",
    confirm: ["Confirme alinhamento em duas projeções.", "Avalie facetas e espaços.", "Procure esclerose e proliferação.", "Relacione nível radiográfico e neurológico."],
    pitfalls: ["Obliquidade simula listese.", "Alteração degenerativa pode ser incidental.", "Projeções forçadas podem ser inseguras em trauma ou instabilidade."],
    nextStep: "Ressonância avalia medula, disco e compressão; tomografia detalha osso e pode apoiar estudos dinâmicos selecionados.",
  },
  {
    test: /pneumomediastino|alargamento de mediastino|neoplásico mediastinal|silhueta tímica|linfoadenopatia/i,
    priority: 4,
    chapter: "Capítulo 30",
    chapterTitle: "Mediastino",
    summary: "Alterações mediastinais são localizadas por deslocamento da traqueia, esôfago, coração e pulmões. Gás delineia estruturas; massas e linfonodos aumentam largura e opacidade.",
    mechanism: "Gás, tecido, líquido ou aumento linfonodal ocupam o mediastino e deslocam estruturas de acordo com o compartimento predominante.",
    confirm: ["Defina mediastino cranial, médio ou caudal.", "Avalie deslocamento traqueal.", "Procure efeito de massa e efusão.", "Diferencie estrutura tímica compatível com idade."],
    pitfalls: ["Gordura mediastinal aumenta largura.", "Rotação altera o mediastino cranial.", "Radiografia raramente define a origem exata de uma massa."],
    nextStep: "Ultrassom permite avaliar e amostrar massas acessíveis; tomografia é superior para origem, extensão e relações vasculares.",
  },
  {
    test: /atelectasia|contusão pulmonar|torção de lobo|enfisema pulmonar bolhoso|consolidação.*pulmonar/i,
    priority: 4,
    chapter: "Capítulo 33",
    chapterTitle: "Pulmão de cães e gatos",
    summary: "Alterações lobares devem ser descritas pela distribuição, volume e padrão. Redução de volume favorece atelectasia; aumento ou posição anormal pode acompanhar torção; trauma pode gerar padrão intersticial/alveolar.",
    mechanism: "Colapso, hemorragia, rotação ou hiperinsuflação alteram o conteúdo de ar, perfusão, volume e posição do lobo.",
    confirm: ["Avalie volume e deslocamento de fissuras.", "Classifique padrão pulmonar.", "Procure brônquio interrompido ou posição anormal.", "Pesquise efusão e pneumotórax associados."],
    pitfalls: ["Atelectasia de decúbito é comum.", "Contusão pode surgir horas após trauma.", "Bolhas intrapulmonares podem simular gás pleural."],
    nextStep: "Tomografia caracteriza lobos, bolhas e trauma complexo; ultrassom e controles seriados podem acompanhar alterações periféricas.",
  },
  {
    test: /agenesia|hipoplasia óssea|ectrodactilia|polimelia|exostose cartilaginosa|displasia fiseal|epifisiólise|necrose asséptica/i,
    priority: 3,
    chapter: "Capítulos 15 e 18",
    chapterTitle: "Anomalias do desenvolvimento e crescimento",
    summary: "Alterações congênitas ou do crescimento devem ser descritas por segmento, morfologia, alinhamento, simetria, fises e repercussão articular.",
    mechanism: "Falhas de formação, ossificação, vascularização ou fechamento fisário modificam comprimento, eixo e congruência.",
    confirm: ["Compare bilateralmente.", "Avalie fises e centros de ossificação.", "Descreva eixo e comprimento.", "Procure osteoartrite ou luxação secundária."],
    pitfalls: ["Centros de ossificação variam com idade.", "Projeção oblíqua distorce eixo.", "Uma anomalia pode coexistir com outras."],
    nextStep: "Tomografia auxilia anatomia tridimensional e planejamento; histórico de crescimento e exames seriados esclarecem progressão.",
  },
  {
    test: /pneumotórax/i,
    chapter: "Capítulo 31",
    chapterTitle: "Espaço pleural",
    summary: "O pneumotórax é reconhecido pela retração das margens pulmonares, ausência de vasos na periferia e separação entre coração e esterno. A projeção e o posicionamento influenciam onde o gás se acumula.",
    mechanism: "O ar no espaço pleural elimina o contato entre pulmão e parede torácica e permite retração do parênquima.",
    confirm: ["Procure linha pulmonar visceral.", "Confirme ausência de vasos além da margem pulmonar.", "Avalie elevação cardíaca e retração lobar.", "Diferencie gás pleural de bolhas intrapulmonares."],
    pitfalls: ["Dobras cutâneas mantêm vasos além da linha.", "Subexposição pode esconder a margem pulmonar.", "Hipovolemia e tórax profundo podem elevar o coração."],
    nextStep: "Ultrassom à beira-leito pode confirmar ausência de deslizamento pleural; casos traumáticos podem exigir reavaliação seriada.",
  },
  {
    test: /efusão.*pleural|derrame pleural/i,
    chapter: "Capítulo 31",
    chapterTitle: "Espaço pleural",
    summary: "Efusão pleural produz fissuras interlobares, retração pulmonar e apagamento variável das silhuetas cardíaca e diafragmática. O volume e o decúbito modificam muito a aparência.",
    mechanism: "Líquido pleural ocupa o espaço entre lobos e parede, separa superfícies pulmonares e reduz o contraste das silhuetas.",
    confirm: ["Procure fissuras interlobares.", "Avalie retração e arredondamento lobar.", "Observe apagamento de silhuetas.", "Procure massas ou linfonodos após drenagem, quando indicada."],
    pitfalls: ["Pouco líquido pode ser ocultado.", "Espessamento pleural pode simular pequena efusão.", "A causa do líquido não é definida pela radiografia."],
    nextStep: "Ultrassom orienta toracocentese e pesquisa estruturas ocultas; análise do líquido define melhor a etiologia.",
  },
  {
    test: /edema pulmonar/i,
    chapter: "Capítulos 32 e 33",
    chapterTitle: "Coração, vasos e pulmões",
    summary: "Edema pulmonar costuma produzir padrão intersticial a alveolar. Distribuição, tamanho cardíaco e vasos pulmonares ajudam a diferenciar origem cardiogênica de não cardiogênica.",
    mechanism: "Aumento de líquido no interstício e nos alvéolos eleva a radiopacidade e pode apagar vasos, formando broncogramas aéreos.",
    confirm: ["Classifique padrão e distribuição.", "Compare veias e artérias pulmonares.", "Avalie tamanho e câmaras cardíacas.", "Procure broncogramas e apagamento vascular."],
    pitfalls: ["Pneumonia e hemorragia podem ter padrão semelhante.", "Expiração e atelectasia aumentam a radiopacidade.", "Distribuição varia entre cães e gatos."],
    nextStep: "Ecocardiografia e evolução após terapia ajudam na origem cardiogênica; gasometria e investigação da causa são importantes nos demais casos.",
  },
  {
    test: /pneumonia|broncopneumonia|aspirativa/i,
    chapter: "Capítulo 33",
    chapterTitle: "Pulmão de cães e gatos",
    summary: "Pneumonia frequentemente produz padrão alveolar ou broncointersticial, com distribuição dependente da via de entrada. O lobo médio direito e regiões cranioventrais merecem atenção na aspiração.",
    mechanism: "Exsudato e células ocupam vias aéreas distais e alvéolos, aumentando a radiopacidade e preservando brônquios cheios de ar.",
    confirm: ["Descreva padrão e distribuição.", "Procure broncogramas aéreos.", "Compare regiões cranioventrais e caudodorsais.", "Revise esôfago, faringe e vias aéreas como possíveis fontes."],
    pitfalls: ["Atelectasia de decúbito pode simular pneumonia.", "Hemorragia e edema compartilham sinais.", "Radiografia pode atrasar em relação aos sinais clínicos."],
    nextStep: "Correlação com hemograma, cultura/citologia de vias aéreas e controle radiográfico conforme evolução clínica.",
  },
  {
    test: /bronquite|broncopatia|asma|bronquiectasia|broncolitíase/i,
    chapter: "Capítulo 33",
    chapterTitle: "Pulmão de cães e gatos",
    summary: "Doença brônquica é reconhecida por paredes espessadas, vistas como anéis e trilhos, podendo coexistir com hiperinsuflação, mineralização e alteração do calibre brônquico.",
    mechanism: "Inflamação, infiltração, muco e remodelamento tornam as paredes brônquicas mais visíveis e alteram o lúmen.",
    confirm: ["Procure anéis e trilhos.", "Avalie calibre e afilamento brônquico.", "Pesquise hiperinsuflação e aprisionamento de ar.", "Diferencie mineralização relacionada à idade."],
    pitfalls: ["Bronquíolos normais vistos de frente podem parecer nódulos.", "Mineralização senil não equivale a inflamação ativa.", "A gravidade radiográfica nem sempre acompanha a clínica."],
    nextStep: "Lavado de vias aéreas, cultura, citologia ou tomografia podem caracterizar doenças persistentes ou focais.",
  },
  {
    test: /metástase pulmonar|processo neoplásico primário|osteoma.*pulmonar|metaplasia.*pulmonar/i,
    chapter: "Capítulo 33",
    chapterTitle: "Pulmão de cães e gatos",
    summary: "Nódulos e massas devem ser descritos por número, tamanho, margens, distribuição e presença de cavitação ou mineralização. A radiografia tem limite para nódulos pequenos.",
    mechanism: "Crescimento tecidual focal substitui o ar pulmonar e cria opacidades estruturadas; disseminação hematógena tende a distribuição multifocal.",
    confirm: ["Conte e meça as maiores lesões.", "Descreva margens e distribuição.", "Compare com vasos vistos de frente.", "Procure linfonodos, efusão e lesão primária."],
    pitfalls: ["Nódulos pequenos podem não ser visíveis.", "Vasos, mamilos e artefatos simulam nódulos.", "Padrão não define histologia."],
    nextStep: "Tomografia é mais sensível para nódulos e planejamento; citologia ou biópsia é necessária para definição etiológica.",
  },
  {
    test: /megaesôfago|anel vascular|corpo estranho esofágico|estenose esofágica|espirocercose|hérnia.*hiato|paraesofágica|intussuscepção gastroesofágica/i,
    chapter: "Capítulo 27",
    chapterTitle: "Esôfago de cães e gatos",
    summary: "Doença esofágica é avaliada pelo diâmetro, conteúdo, deslocamento da traqueia, nível da dilatação e presença de complicações pulmonares.",
    mechanism: "Obstrução, dismotilidade ou alteração anatômica retêm gás, líquido ou alimento e distendem o esôfago.",
    confirm: ["Defina se a dilatação é focal ou difusa.", "Procure corpo estranho ou ponto de transição.", "Avalie deslocamento traqueal.", "Pesquise pneumonia aspirativa."],
    pitfalls: ["Aerofagia pode distender discretamente o esôfago.", "Corpos estranhos pouco radiopacos podem ser ocultos.", "Contraste é contraindicado quando há risco de perfuração ou aspiração sem planejamento."],
    nextStep: "Fluoroscopia avalia motilidade; endoscopia e contraste são selecionados conforme suspeita e risco.",
  },
  {
    test: /colapso traqueal|estenose traqueal|hipoplasia traqueal|membrana redundante|massa traqueal|ruptura traqueal/i,
    chapter: "Capítulo 26",
    chapterTitle: "Faringe, laringe e traqueia",
    summary: "O diâmetro traqueal deve ser acompanhado do pescoço à carina. Alterações dinâmicas podem variar com fase respiratória e localização cervical ou intratorácica.",
    mechanism: "Fraqueza cartilaginosa, membrana dorsal redundante, massa, trauma ou desenvolvimento anormal reduzem ou interrompem o lúmen.",
    confirm: ["Localize o segmento alterado.", "Compare fases respiratórias quando disponíveis.", "Procure gás extraluminal ou pneumomediastino.", "Avalie pulmões e brônquios associados."],
    pitfalls: ["Flexão do pescoço simula estreitamento.", "Radiografia estática pode perder colapso dinâmico.", "Sobreposição do esôfago pode confundir o contorno dorsal."],
    nextStep: "Fluoroscopia ou endoscopia avaliam dinâmica e lúmen; tomografia auxilia massas, trauma e planejamento.",
  },
  {
    test: /aumento de átrio|aumento de ventrículo|cardiomegalia|microcardia|efusão pericárdica/i,
    chapter: "Capítulo 32",
    chapterTitle: "Coração e vasos pulmonares",
    summary: "A silhueta cardíaca deve ser avaliada em conjunto com vasos pulmonares, pulmões, conformação e fase respiratória. Formato e deslocamentos regionais sugerem câmaras predominantes, mas não confirmam função.",
    mechanism: "Dilatação de câmaras, hipertrofia, líquido pericárdico ou alteração de volume circulante modificam dimensões e contornos da silhueta.",
    confirm: ["Avalie tamanho global e contornos regionais.", "Compare veias e artérias pulmonares.", "Procure edema, congestão ou hipoperfusão.", "Considere o escore vertebral quando tecnicamente adequado."],
    pitfalls: ["Expiração, rotação e conformação alteram a silhueta.", "Gordura pericárdica pode aumentar o contorno.", "Radiografia não avalia função ou fluxo intracardíaco."],
    nextStep: "Ecocardiografia é o exame principal para câmaras, válvulas, função e efusão; eletrocardiograma complementa ritmo.",
  },
  {
    test: /fratura|disjunção|luxação|subluxação|monteggia|esquírola|sequestro/i,
    priority: 3,
    chapter: "Capítulo 16",
    chapterTitle: "Consolidação de fraturas e complicações",
    summary: "A fratura deve ser descrita de modo reconstrutível: osso, lado, terço, orientação, extensão, deslocamento, articulação e tecidos moles. Em luxações, nomeie a posição do segmento distal.",
    mechanism: "A interrupção óssea e a perda de alinhamento resultam do trauma; resposta periosteal, reabsorção de margens e ponte cortical refletem tempo, estabilidade e consolidação.",
    confirm: ["Inclua duas projeções ortogonais.", "Avalie articulações proximal e distal.", "Descreva deslocamento do fragmento distal.", "Procure fraturas adicionais e lesão fisária."],
    pitfalls: ["Canais vasculares e placas de crescimento simulam fraturas.", "Projeção única subestima cominuição.", "Ausência de calo não significa falha quando há estabilidade rígida."],
    nextStep: "Tomografia auxilia fraturas complexas e articulares; controles seriados avaliam alinhamento, ponte óssea, implantes e complicações.",
  },
  {
    test: /não união|má união|consolidação óssea|calo ósseo|metalose|túnel cirúrgico/i,
    priority: 4,
    chapter: "Capítulo 16",
    chapterTitle: "Consolidação de fraturas e complicações",
    summary: "O acompanhamento deve comparar linha de fratura, ponte cortical, remodelamento, eixo, estabilidade dos implantes e reação periosteal ao longo do tempo.",
    mechanism: "Estabilidade, vascularização, intervalo, infecção e carga determinam o padrão de calo e a progressão da consolidação.",
    confirm: ["Compare com exames anteriores.", "Procure ponte em corticais.", "Avalie afrouxamento ou falha de implantes.", "Descreva eixo e remodelamento."],
    pitfalls: ["Calo exuberante pode indicar instabilidade.", "Reabsorção ao redor de implantes pode ser mecânica ou infecciosa.", "A aparência varia com o método de fixação."],
    nextStep: "Controle radiográfico padronizado e avaliação ortopédica definem progressão; suspeita de infecção pode exigir amostragem.",
  },
  {
    test: /osteoartrite|osteoartrose|osteofitose|enteseofitose|efusão articular/i,
    chapter: "Capítulo 18",
    chapterTitle: "Sinais radiográficos da doença articular",
    summary: "Doença articular degenerativa é inferida por osteófitos, enteseófitos, esclerose subcondral, remodelamento e efusão. A distribuição ajuda a sugerir instabilidade ou doença primária.",
    mechanism: "Dano de cartilagem e instabilidade estimulam remodelamento do osso subcondral, margens articulares e inserções capsuloligamentares.",
    confirm: ["Avalie espaço e alinhamento.", "Procure osteófitos marginais.", "Descreva osso subcondral e efusão.", "Pesquise causa primária de instabilidade."],
    pitfalls: ["Osteófito discreto não mede dor.", "Cartilagem não é vista diretamente.", "Enteseófito isolado pode refletir tração crônica."],
    nextStep: "Ultrassom, tomografia, ressonância ou artroscopia podem avaliar estruturas de partes moles e cartilagem.",
  },
  {
    test: /artrite séptica|artrite reumatoide|poliartrite/i,
    chapter: "Capítulo 18",
    chapterTitle: "Sinais radiográficos da doença articular",
    summary: "Artrites podem começar com efusão e edema; erosões, irregularidade subcondral, estreitamento e proliferação aparecem conforme evolução. A distribuição mono ou poliarticular é decisiva.",
    mechanism: "Inflamação sinovial e enzimas degradam cartilagem e osso subcondral; infecção pode progredir rapidamente.",
    confirm: ["Defina número de articulações.", "Procure efusão e erosões.", "Compare articulação contralateral.", "Avalie tecidos moles e osso adjacente."],
    pitfalls: ["Radiografia inicial pode ser normal.", "Degeneração e inflamação podem coexistir.", "Etiologia não deve ser definida sem análise sinovial."],
    nextStep: "Artrocentese com citologia e cultura é central; ultrassom auxilia efusão e estruturas periarticulares.",
  },
  {
    test: /osteomielite|processo neoplásico|cisto ósseo|triângulo de codman|osteólise/i,
    priority: 1,
    chapter: "Capítulos 14 e 17",
    chapterTitle: "Lesões ósseas agressivas, tumores e infecção",
    summary: "A radiografia classifica agressividade, mas frequentemente não separa neoplasia de infecção. Zona de transição, lise, reação periosteal, cortical e extensão em tecidos moles devem ser descritas.",
    mechanism: "Destruição e produção óssea refletem a interação entre velocidade do processo, resposta do hospedeiro e matriz da lesão.",
    confirm: ["Defina padrão de lise.", "Avalie zona de transição.", "Caracterize reação periosteal.", "Procure ruptura cortical e massa de tecidos moles."],
    pitfalls: ["Triângulo de Codman indica agressividade, não etiologia.", "Infecção pode parecer neoplasia e vice-versa.", "Radiografia subestima extensão intramedular."],
    nextStep: "Citologia ou biópsia com cultura quando indicada; tomografia e ressonância ajudam no estadiamento e planejamento.",
  },
  {
    test: /hiperparatireoidismo|raquitismo|osteopenia|osteopetrose|hipervitaminose|mucopolissacaridose/i,
    chapter: "Capítulos 15 e 18",
    chapterTitle: "Doenças ortopédicas do crescimento e distúrbios metabólicos",
    summary: "Doença óssea generalizada deve ser reconhecida pela distribuição difusa e pelo contraste entre cortical e medular, associando idade, dieta, doença renal e alterações de múltiplos ossos.",
    mechanism: "Desequilíbrios de mineralização, remodelamento ou armazenamento alteram densidade, espessura cortical, placas de crescimento e resistência óssea.",
    confirm: ["Avalie múltiplos ossos.", "Compare cortical e medular.", "Procure fraturas patológicas.", "Revise fises, metáfises, coluna e mandíbula."],
    pitfalls: ["Exposição inadequada simula osteopenia.", "Variações etárias mudam a densidade aparente.", "Diagnóstico exige correlação laboratorial."],
    nextStep: "Perfil mineral, função renal, dieta e demais exames laboratoriais devem ser correlacionados; densitometria ou outros exames são selecionados conforme o caso.",
  },
  {
    test: /osteocondrose|osteodistrofia hipertrófica|panosteíte|retenção do núcleo|displasia de cotovelo|coronoide|ancôneo|necrose isquêmica|fechamento precoce/i,
    chapter: "Capítulo 15",
    chapterTitle: "Doenças ortopédicas de animais jovens",
    summary: "Idade, raça, bilateralidade e localização típica são essenciais. Irregularidade subcondral, esclerose, fragmentos, alterações metafisárias ou medulares devem ser comparados bilateralmente.",
    mechanism: "Distúrbios de ossificação endocondral, crescimento, vascularização ou carga alteram epífises, metáfises, fises e congruência articular.",
    confirm: ["Confirme idade e local típico.", "Compare o membro contralateral.", "Avalie congruência e osso subcondral.", "Procure remodelamento e osteoartrite secundária."],
    pitfalls: ["Centros de ossificação normais simulam fragmentos.", "Posicionamento inadequado esconde lesões.", "Mais de uma alteração do desenvolvimento pode coexistir."],
    nextStep: "Projeções especiais e tomografia aumentam a sensibilidade em articulações complexas; artroscopia pode confirmar e tratar lesões selecionadas.",
  },
  {
    test: /displasia coxofemoral/i,
    chapter: "Capítulo 18",
    chapterTitle: "Displasia do quadril",
    summary: "A frouxidão e a incongruência precedem a osteoartrite. Cobertura acetabular, subluxação, remodelamento da cabeça/colo e osteófitos devem ser avaliados em projeção padronizada.",
    mechanism: "Laxidade articular permite deslocamento da cabeça femoral, concentração anormal de carga e remodelamento progressivo.",
    confirm: ["Confirme simetria pélvica.", "Avalie cobertura acetabular.", "Procure subluxação e remodelamento.", "Descreva osteófitos e esclerose."],
    pitfalls: ["Rotação altera a aparência.", "Ausência de osteoartrite não exclui frouxidão.", "Projeções diferentes respondem perguntas diferentes."],
    nextStep: "Métodos de distração e avaliação ortopédica complementam frouxidão; tomografia pode ajudar no planejamento.",
  },
  {
    test: /luxação patelar|ligamento cruzado|mineralização meniscal/i,
    priority: 4,
    chapter: "Capítulo 18",
    chapterTitle: "Joelho",
    summary: "Alinhamento patelar, efusão, deslocamento do coxim adiposo infrapatelar, osteófitos e posição tibial ajudam a reconhecer instabilidade do joelho, embora ligamentos e meniscos não sejam vistos diretamente.",
    mechanism: "Instabilidade e deslocamento alteram a relação patelotroclear ou femorotibial e produzem efusão e osteoartrite secundária.",
    confirm: ["Avalie posição da patela.", "Procure efusão e osteófitos.", "Compare alinhamento femorotibial.", "Avalie tuberosidade e crista tibial."],
    pitfalls: ["Rotação simula luxação patelar.", "Ausência de osteófitos não exclui ruptura aguda.", "Mineralização meniscal não define integridade funcional."],
    nextStep: "Exame ortopédico, ultrassom, ressonância ou artroscopia caracterizam estruturas de tecidos moles.",
  },
  {
    test: /doença do disco|protrusão|extrusão|espondilose|osteofitose/i,
    chapter: "Capítulos 11 e 12",
    chapterTitle: "Vértebras, disco e medula",
    summary: "Redução de espaço, mineralização discal, estreitamento foraminal e material mineral no canal podem apoiar doença discal, mas sensibilidade e especificidade da radiografia são limitadas.",
    mechanism: "Degeneração do disco, protrusão ou extrusão altera o espaço intervertebral e pode produzir compressão neural não mensurável em radiografias simples.",
    confirm: ["Compare espaços adjacentes.", "Avalie forames e placas terminais.", "Procure material mineral no canal.", "Diferencie espondilose de discospondilite."],
    pitfalls: ["Espaço estreito isolado é inespecífico.", "Posicionamento oblíquo modifica o espaço.", "Espondilose não comprova compressão medular."],
    nextStep: "Ressonância é preferível para disco e medula; tomografia é útil em material mineralizado e planejamento.",
  },
  {
    test: /discoespondilite|espondilite|fisite vertebral/i,
    chapter: "Capítulo 11",
    chapterTitle: "Condições inflamatórias da coluna",
    summary: "Lise e irregularidade das placas terminais, estreitamento ou colapso do espaço e proliferação ventral favorecem processo infeccioso/inflamatório, com evolução dependente do tempo.",
    mechanism: "Infecção ou inflamação destrói placas terminais e disco e estimula esclerose e proliferação reativa.",
    confirm: ["Avalie ambas as placas terminais.", "Descreva espaço e lise.", "Procure esclerose e proliferação.", "Revise tecidos paravertebrais e outros níveis."],
    pitfalls: ["Alterações iniciais podem ser discretas.", "Degeneração avançada pode confundir.", "Radiografia não avalia extensão epidural."],
    nextStep: "Ressonância caracteriza disco, medula e extensão epidural; cultura e investigação do foco infeccioso são importantes.",
  },
  {
    test: /hemivértebra|vértebra de transição|espinha bífida|vértebras em bloco|odontoide|cifose|lordose|escoliose/i,
    chapter: "Capítulo 11",
    chapterTitle: "Anomalias vertebrais",
    summary: "Malformações devem ser descritas pela morfologia, nível, número, alinhamento e possível estreitamento do canal. A presença do achado não prova relação com sinais neurológicos.",
    mechanism: "Alterações congênitas de formação ou segmentação modificam o corpo, arco ou processos vertebrais e podem causar deformidade angular.",
    confirm: ["Identifique nível e morfologia.", "Avalie número de vértebras.", "Descreva desvio angular.", "Procure outras malformações e sinais degenerativos."],
    pitfalls: ["Variações podem ser incidentais.", "Rotação agrava assimetria aparente.", "Compressão medular não é definida pela radiografia."],
    nextStep: "Tomografia detalha osso e canal; ressonância determina repercussão sobre medula e tecidos moles.",
  },
  {
    test: /nasal|rinite|seios|vômer/i,
    chapter: "Capítulo 8",
    chapterTitle: "Cavidades craniana e nasal",
    summary: "Doença nasal deve ser avaliada pela distribuição unilateral ou bilateral, preservação de conchas, integridade do vômer, septo, placas ósseas e extensão aos seios.",
    mechanism: "Líquido, tecido e destruição das conchas aumentam radiopacidade e apagam o padrão trabecular; processos agressivos atravessam limites anatômicos.",
    confirm: ["Compare lados.", "Avalie conchas e vômer.", "Procure lise e efeito de massa.", "Revise seios frontais, órbita e placa cribriforme quando possível."],
    pitfalls: ["Sobreposição e rotação reduzem sensibilidade.", "Inflamação crônica pode ser destrutiva.", "Radiografia não define extensão intracraniana."],
    nextStep: "Tomografia é o principal complemento para extensão; rinoscopia e amostragem definem etiologia.",
  },
  {
    test: /otite|bula|canal auditivo/i,
    chapter: "Capítulo 8",
    chapterTitle: "Cavidades craniana e nasal",
    summary: "Bulas e canais auditivos devem ser comparados bilateralmente quanto a conteúdo, espessura, lise, proliferação e mineralização.",
    mechanism: "Inflamação ou massa aumenta a radiopacidade do lúmen e pode espessar, remodelar ou destruir a parede óssea.",
    confirm: ["Compare bulas e canais.", "Avalie espessura e contorno ósseo.", "Procure lise ou proliferação.", "Revise tecidos moles adjacentes."],
    pitfalls: ["Obliquidade cria assimetria falsa.", "Conteúdo discreto pode não ser detectado.", "Alteração crônica e neoplasia podem se sobrepor."],
    nextStep: "Tomografia avalia extensão óssea; otoscopia e amostragem caracterizam conteúdo e etiologia.",
  },
  {
    test: /dent|periodontal|periapical|mandibular|mandíbula|sínfise mentoniana/i,
    chapter: "Capítulos 7 e 8",
    chapterTitle: "Crânio, mandíbula e estruturas dentárias",
    summary: "A avaliação dentária e mandibular exige projeções sem sobreposição ou radiografia odontológica. Espaço periodontal, lâmina dura, alvéolo, raiz, cortical e tecidos moles devem ser revistos.",
    mechanism: "Inflamação, cisto, trauma ou massa altera o espaço periodontal, produz lise periapical/alveolar, expansão ou interrupção cortical.",
    confirm: ["Localize dente e raiz.", "Avalie espaço periodontal e lâmina dura.", "Procure lise, expansão ou fratura.", "Revise cortical mandibular e tecidos moles."],
    pitfalls: ["Sobreposição esconde raízes.", "Dentes em desenvolvimento simulam lesões.", "Radiografia convencional é menos sensível que a odontológica."],
    nextStep: "Radiografia intraoral ou tomografia melhora localização; avaliação odontológica e amostragem podem ser necessárias.",
  },
  {
    test: /hérnia diafragmática|peritoneopericárdica/i,
    chapter: "Capítulo 29",
    chapterTitle: "Diafragma",
    summary: "Doença diafragmática é sugerida por perda do contorno, posição torácica de órgãos abdominais e deslocamento de pulmões, mediastino ou coração.",
    mechanism: "Defeito ou ruptura permite migração de vísceras e altera a continuidade entre compartimentos torácico e abdominal.",
    confirm: ["Acompanhe todo o contorno diafragmático.", "Identifique gás ou órgãos no tórax.", "Avalie deslocamentos.", "Revise abdômen para ausência ou posição anormal de órgãos."],
    pitfalls: ["Efusão apaga o diafragma.", "Sobreposição pode simular perda de contorno.", "Pequenos defeitos podem ser intermitentes."],
    nextStep: "Ultrassom ou tomografia confirma continuidade e conteúdo herniado; contraste é selecionado em casos específicos.",
  },
  {
    test: /efusão peritoneal|pneumoperitôneo|eventração|evisceração|hérnia umbilical/i,
    chapter: "Capítulo 36",
    chapterTitle: "Espaço peritoneal",
    summary: "Alterações peritoneais modificam detalhe seroso, distribuição de gás e posição de vísceras. Idade, gordura e técnica devem ser considerados antes de concluir efusão.",
    mechanism: "Líquido reduz contraste entre órgãos; gás livre realça superfícies serosas; defeitos de parede deslocam conteúdo além da musculatura.",
    confirm: ["Avalie detalhe seroso.", "Procure gás fora do trato gastrointestinal.", "Defina continuidade da parede abdominal.", "Identifique órgãos deslocados."],
    pitfalls: ["Paciente jovem ou magro tem pouco detalhe.", "Cirurgia recente pode explicar gás livre.", "Pregas de pele simulam defeitos de parede."],
    nextStep: "Ultrassom caracteriza líquido e órgãos herniados e orienta coleta; tomografia auxilia extensão e planejamento.",
  },
  {
    test: /hepat|colelit|colecist|espleno/i,
    chapter: "Capítulo 37",
    chapterTitle: "Fígado e baço",
    summary: "Radiografias avaliam principalmente tamanho, margens, posição e mineralização. Alterações focais de parênquima podem não modificar a silhueta.",
    mechanism: "Aumento de volume e massas deslocam estômago, rins e intestinos; gás ou mineralização criam contraste incomum no órgão.",
    confirm: ["Avalie margens e extensão além do arco costal.", "Descreva deslocamentos.", "Procure gás ou mineralização.", "Compare com conformação e fase respiratória."],
    pitfalls: ["Variação conformacional muda o tamanho aparente.", "Radiografia não diferencia causas de organomegalia.", "Lesões focais pequenas podem ser invisíveis."],
    nextStep: "Ultrassonografia caracteriza parênquima, vesícula e fluxo; tomografia e amostragem são selecionadas conforme a lesão.",
  },
  {
    test: /nefro|renal|ureter|duplo j|bypass ureteral/i,
    chapter: "Capítulo 38",
    chapterTitle: "Rins e ureteres",
    summary: "Tamanho, forma, margens, posição e mineralizações renais são os sinais radiográficos principais. Ureteres normais não são visíveis sem contraste.",
    mechanism: "Aumento, redução, mineralização, obstrução ou dispositivos alteram a silhueta renal e o trajeto urinário.",
    confirm: ["Compare os dois rins.", "Meça quando a projeção permitir.", "Procure minerais no trajeto ureteral.", "Avalie dispositivos, posição e complicações."],
    pitfalls: ["Sobreposição intestinal esconde urólitos.", "Nem todo urólito é radiopaco.", "Tamanho renal normal não exclui doença."],
    nextStep: "Ultrassom avalia parênquima e dilatação; contraste ou tomografia caracterizam obstrução e planejamento.",
  },
  {
    test: /cist|bexiga|uretro|sonda uretral/i,
    chapter: "Capítulos 39 e 40",
    chapterTitle: "Bexiga urinária e uretra",
    summary: "Radiografias simples demonstram posição, tamanho, contorno e urólitos radiopacos. Contraste é útil para parede, ruptura, defeitos de preenchimento e uretra.",
    mechanism: "Minerais, gás, espessamento, massa ou ruptura mudam conteúdo e contorno do trato urinário inferior.",
    confirm: ["Procure urólitos em duas projeções.", "Avalie gás e histórico de sondagem.", "Descreva contorno e posição.", "Siga a uretra pélvica e peniana quando possível."],
    pitfalls: ["Fezes e minerais cutâneos simulam urólitos.", "Urólitos radiotransparentes não são excluídos.", "Gás iatrogênico pode simular cistite enfisematosa."],
    nextStep: "Ultrassom e estudos contrastados avaliam parede, urólitos não radiopacos, ruptura e uretra.",
  },
  {
    test: /prostat|ovar|piometra/i,
    chapter: "Capítulos 41 e 42",
    chapterTitle: "Próstata e trato reprodutivo",
    summary: "Radiografias avaliam tamanho, posição, contorno, mineralização e efeito de massa, mas têm baixa especificidade para a causa de prostatomegalia ou aumento uterino.",
    mechanism: "Aumento do órgão desloca bexiga, cólon e intestinos; mineralização prostática em animal castrado aumenta preocupação com doença agressiva.",
    confirm: ["Descreva tamanho e deslocamentos.", "Procure mineralização ou gás.", "Avalie linfonodos e esqueleto.", "Considere estado reprodutivo."],
    pitfalls: ["Radiografia não diferencia conteúdo uterino.", "Sobreposição limita ovários.", "Tamanho prostático varia com estado hormonal."],
    nextStep: "Ultrassom é o principal complemento; citologia, cultura e exames laboratoriais dependem da suspeita.",
  },
  {
    test: /dilatação gástrica|torção gástrica|corpo estranho gástrico/i,
    chapter: "Capítulo 43",
    chapterTitle: "Estômago",
    summary: "Posição, compartimentalização, grau de dilatação e conteúdo ajudam a diferenciar dilatação simples, vólvulo e obstrução. A projeção lateral direita é especialmente informativa no vólvulo gástrico.",
    mechanism: "Gás, líquido, alimento, corpo estranho ou rotação distendem o estômago e deslocam piloro, fundo e órgãos adjacentes.",
    confirm: ["Avalie posição do piloro.", "Procure compartimentalização.", "Descreva conteúdo e grau de dilatação.", "Pesquise esplenomegalia e gás na parede ou veia porta."],
    pitfalls: ["Projeção e decúbito redistribuem gás.", "Estômago alimentado pode parecer distendido.", "Corpos estranhos não radiopacos podem ser ocultos."],
    nextStep: "Suspeita de vólvulo é emergência; ultrassom ou endoscopia auxiliam corpos estranhos selecionados quando o paciente está estável.",
  },
  {
    test: /corpo estranho intestinal|obstrutivo intestinal|neoplásico intestinal/i,
    chapter: "Capítulo 44",
    chapterTitle: "Intestino delgado",
    summary: "Obstrução é sugerida por dilatação desproporcional, distribuição segmentar, duas populações de alças, empilhamento ou plicatura. A persistência e o contexto aumentam a confiança.",
    mechanism: "Bloqueio mecânico acumula gás e líquido proximalmente e reduz conteúdo distal; objetos lineares encurtam e plicam o intestino.",
    confirm: ["Compare diâmetros e distribuição.", "Procure ponto de transição.", "Avalie plicatura e pequenas bolhas de gás.", "Pesquise gás livre ou perda de detalhe."],
    pitfalls: ["Íleo funcional pode dilatar alças.", "Conteúdo alimentar simula corpo estranho.", "Radiografia isolada pode ser inconclusiva."],
    nextStep: "Ultrassom é altamente complementar; exames seriados, contraste ou cirurgia dependem da estabilidade e probabilidade de obstrução.",
  },
  {
    test: /fecaloma|megacólon/i,
    chapter: "Capítulo 45",
    chapterTitle: "Intestino grosso",
    summary: "O cólon deve ser identificado pela posição e conteúdo. Diâmetro, retenção fecal, deslocamento e causas obstrutivas ajudam a separar constipação de dilatação crônica grave.",
    mechanism: "Retenção prolongada aumenta diâmetro e compacta conteúdo fecal, podendo reduzir motilidade e causar deslocamento de alças.",
    confirm: ["Meça o diâmetro quando aplicável.", "Avalie extensão e conteúdo.", "Procure estreitamento pélvico ou massa.", "Compare com histórico e recorrência."],
    pitfalls: ["Uma única radiografia não define cronicidade.", "Conteúdo fecal varia com dieta e preparo.", "Constipação e megacólon exigem correlação clínica."],
    nextStep: "Exame retal, ultrassom ou contraste podem investigar causa mecânica; acompanhamento clínico define função.",
  },
  {
    test: /prenhez|distocia|fetal|spalding/i,
    chapter: "Capítulo 42",
    chapterTitle: "Útero e gestação",
    summary: "Após mineralização, a radiografia permite estimar número e posição fetal e avaliar relação fetopélvica. Sinais de morte fetal devem ser interpretados com cautela.",
    mechanism: "Mineralização esquelética progressiva cria contraste; gás fetal, colapso ou desalinhamento podem acompanhar morte e decomposição.",
    confirm: ["Conte crânios e colunas.", "Defina apresentação.", "Compare diâmetro craniano e pelve.", "Procure gás e perda de organização."],
    pitfalls: ["Sobreposição causa erro de contagem.", "Radiografia não avalia batimentos.", "Idade gestacional radiográfica é aproximada."],
    nextStep: "Ultrassonografia avalia viabilidade, frequência cardíaca e tecidos moles e orienta a conduta obstétrica.",
  },
];

export function getThrallContext(title: string, region: string): ThrallContext {
  const base = regionBase[region] || regionBase["Outros"];
  const rule = rules
    .filter((candidate) => candidate.test.test(title))
    .sort((a, b) => (b.priority || 2) - (a.priority || 2))[0];
  if (!rule) return base;
  return {
    ...base,
    ...rule,
    evidence: `Síntese de estudo baseada em Thrall, Diagnóstico de Radiologia Veterinária, 6ª edição, ${rule.chapter || base.chapter}.`,
  };
}
